[2023-03-26 07:25:46,442] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2023-03-26 07:25:46,564] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2023-03-26 07:25:46,574] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-26 07:25:46,642] {taskinstance.py:1357} INFO - Starting attempt 4 of 6
[2023-03-26 07:25:46,659] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-26 07:25:46,903] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): schedule_job_task> on 2023-03-25 00:00:00+00:00
[2023-03-26 07:25:47,407] {standard_task_runner.py:52} INFO - Started process 1951 to run task
[2023-03-26 07:25:47,488] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'schedule_job_task', 'scheduled__2023-03-25T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmp9_zza165', '--error-file', '/tmp/tmp_cds2wuk']
[2023-03-26 07:25:47,505] {standard_task_runner.py:80} INFO - Job 106: Subtask schedule_job_task
[2023-03-26 07:25:47,877] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.schedule_job_task scheduled__2023-03-25T00:00:00+00:00 [running]> on host 6614738016e4
[2023-03-26 07:25:48,757] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=schedule_job_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T00:00:00+00:00
[2023-03-26 08:04:34,595] {logging_mixin.py:115} INFO - This is the response: {'node_name': 'fac540815f2e', 'status': 'ok', 'jobid': '6f87c504cba711ed8fcb0242ac180002'}
[2023-03-26 08:04:34,616] {logging_mixin.py:115} INFO - Job scheduled successfully
[2023-03-26 08:04:34,729] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rightmove_extraction_dag.py", line 27, in schedule_job
    result = {'jobid': response_json['job_id']}
KeyError: 'job_id'
[2023-03-26 08:04:35,327] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=schedule_job_task, execution_date=20230325T000000, start_date=20230326T072546, end_date=20230326T080435
[2023-03-26 08:04:35,795] {standard_task_runner.py:92} ERROR - Failed to execute job 106 for task schedule_job_task ('job_id'; 1951)
[2023-03-26 08:04:37,448] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-26 08:04:40,388] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
