[2023-02-10 10:55:49,685] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 10:55:49,702] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 10:55:49,705] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 10:55:49,709] {taskinstance.py:1357} INFO - Starting attempt 4 of 6
[2023-02-10 10:55:49,712] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 10:55:49,788] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-09 00:00:00+00:00
[2023-02-10 10:55:49,855] {standard_task_runner.py:52} INFO - Started process 328 to run task
[2023-02-10 10:55:49,864] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'scheduled__2023-02-09T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmp_h794ejo', '--error-file', '/tmp/tmpafnzzljo']
[2023-02-10 10:55:49,883] {standard_task_runner.py:80} INFO - Job 8: Subtask get_token
[2023-02-10 10:55:50,262] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [running]> on host f94e6d45e56a
[2023-02-10 10:55:50,629] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:00:00+00:00
[2023-02-10 10:55:50,668] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 10:55:50,696] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd app && ./script.sh ']
[2023-02-10 10:55:50,827] {subprocess.py:85} INFO - Output:
[2023-02-10 10:55:51,091] {subprocess.py:92} INFO - bash: line 1: cd: app: No such file or directory
[2023-02-10 10:55:51,107] {subprocess.py:96} INFO - Command exited with return code 1
[2023-02-10 10:55:51,200] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-10 10:55:51,223] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230209T000000, start_date=20230210T105549, end_date=20230210T105551
[2023-02-10 10:55:51,280] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task get_token (Bash command failed. The command returned a non-zero exit code 1.; 328)
[2023-02-10 10:55:51,348] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 10:55:51,417] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 12:24:01,067] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 12:24:01,076] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 12:24:01,078] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 12:24:01,083] {taskinstance.py:1357} INFO - Starting attempt 4 of 6
[2023-02-10 12:24:01,084] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 12:24:01,107] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-09 00:00:00+00:00
[2023-02-10 12:24:01,120] {standard_task_runner.py:52} INFO - Started process 330 to run task
[2023-02-10 12:24:01,126] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'scheduled__2023-02-09T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmp6ux_ncb6', '--error-file', '/tmp/tmpl5jwd29u']
[2023-02-10 12:24:01,139] {standard_task_runner.py:80} INFO - Job 8: Subtask get_token
[2023-02-10 12:24:01,230] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [running]> on host 132093137b1e
[2023-02-10 12:24:01,351] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:00:00+00:00
[2023-02-10 12:24:01,356] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 12:24:01,360] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /app && ./script.sh ']
[2023-02-10 12:24:01,380] {subprocess.py:85} INFO - Output:
[2023-02-10 12:24:01,423] {subprocess.py:92} INFO - ./script.sh: line 5: gcloud: command not found
[2023-02-10 12:24:01,427] {subprocess.py:92} INFO - ./script.sh: line 9: gcloud: command not found
[2023-02-10 12:24:01,448] {subprocess.py:92} INFO - ./script.sh: line 13: gcloud: command not found
[2023-02-10 12:24:01,451] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-10 12:24:01,474] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10 12:24:01,486] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230209T000000, start_date=20230210T122401, end_date=20230210T122401
[2023-02-10 12:24:01,505] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task get_token (Bash command failed. The command returned a non-zero exit code 127.; 330)
[2023-02-10 12:24:01,547] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 12:24:01,586] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 13:06:51,642] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 13:06:51,679] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 13:06:51,692] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:06:51,698] {taskinstance.py:1357} INFO - Starting attempt 4 of 6
[2023-02-10 13:06:51,699] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:06:51,710] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-09 00:00:00+00:00
[2023-02-10 13:06:51,724] {standard_task_runner.py:52} INFO - Started process 378 to run task
[2023-02-10 13:06:51,745] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'scheduled__2023-02-09T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpgjb24hkn', '--error-file', '/tmp/tmpjnpyph_g']
[2023-02-10 13:06:51,784] {standard_task_runner.py:80} INFO - Job 8: Subtask get_token
[2023-02-10 13:06:51,971] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [running]> on host a299c389a304
[2023-02-10 13:06:52,121] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:00:00+00:00
[2023-02-10 13:06:52,136] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 13:06:52,151] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /app && ./script.sh ']
[2023-02-10 13:06:52,177] {subprocess.py:85} INFO - Output:
[2023-02-10 13:06:52,261] {subprocess.py:92} INFO - bash: line 1: ./script.sh: No such file or directory
[2023-02-10 13:06:52,268] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-10 13:06:52,299] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10 13:06:52,337] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230209T000000, start_date=20230210T130651, end_date=20230210T130652
[2023-02-10 13:06:52,349] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task get_token (Bash command failed. The command returned a non-zero exit code 127.; 378)
[2023-02-10 13:06:52,387] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 13:06:52,427] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
