[2023-02-10 10:51:40,789] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 10:51:40,805] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 10:51:40,809] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 10:51:40,812] {taskinstance.py:1357} INFO - Starting attempt 2 of 6
[2023-02-10 10:51:40,814] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 10:51:40,828] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-09 00:00:00+00:00
[2023-02-10 10:51:40,861] {standard_task_runner.py:52} INFO - Started process 274 to run task
[2023-02-10 10:51:40,876] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'scheduled__2023-02-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmp_gljdj2n', '--error-file', '/tmp/tmp95q9rwlu']
[2023-02-10 10:51:40,879] {standard_task_runner.py:80} INFO - Job 4: Subtask get_token
[2023-02-10 10:51:40,938] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [running]> on host f94e6d45e56a
[2023-02-10 10:51:41,047] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:00:00+00:00
[2023-02-10 10:51:41,050] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 10:51:41,059] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd app && ./script.sh ']
[2023-02-10 10:51:41,086] {subprocess.py:85} INFO - Output:
[2023-02-10 10:51:41,105] {subprocess.py:92} INFO - bash: line 1: cd: app: No such file or directory
[2023-02-10 10:51:41,114] {subprocess.py:96} INFO - Command exited with return code 1
[2023-02-10 10:51:41,147] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-10 10:51:41,159] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230209T000000, start_date=20230210T105140, end_date=20230210T105141
[2023-02-10 10:51:41,174] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task get_token (Bash command failed. The command returned a non-zero exit code 1.; 274)
[2023-02-10 10:51:41,208] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 10:51:41,251] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 12:19:53,136] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 12:19:53,212] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 12:19:53,225] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 12:19:53,229] {taskinstance.py:1357} INFO - Starting attempt 2 of 6
[2023-02-10 12:19:53,251] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 12:19:53,343] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-09 00:00:00+00:00
[2023-02-10 12:19:53,442] {standard_task_runner.py:52} INFO - Started process 265 to run task
[2023-02-10 12:19:53,467] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'scheduled__2023-02-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpk83oomsv', '--error-file', '/tmp/tmp_w8c6w8n']
[2023-02-10 12:19:53,489] {standard_task_runner.py:80} INFO - Job 4: Subtask get_token
[2023-02-10 12:19:54,172] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [running]> on host 132093137b1e
[2023-02-10 12:19:55,432] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:00:00+00:00
[2023-02-10 12:19:55,534] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 12:19:55,825] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /app && ./script.sh ']
[2023-02-10 12:19:56,248] {subprocess.py:85} INFO - Output:
[2023-02-10 12:19:56,482] {subprocess.py:92} INFO - ./script.sh: line 5: gcloud: command not found
[2023-02-10 12:19:56,758] {subprocess.py:92} INFO - ./script.sh: line 9: gcloud: command not found
[2023-02-10 12:19:56,821] {subprocess.py:92} INFO - ./script.sh: line 13: gcloud: command not found
[2023-02-10 12:19:56,834] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-10 12:19:57,145] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10 12:19:57,226] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230209T000000, start_date=20230210T121953, end_date=20230210T121957
[2023-02-10 12:19:57,312] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task get_token (Bash command failed. The command returned a non-zero exit code 127.; 265)
[2023-02-10 12:19:57,477] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 12:19:57,644] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 13:02:48,803] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 13:02:48,824] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [queued]>
[2023-02-10 13:02:48,828] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:02:48,833] {taskinstance.py:1357} INFO - Starting attempt 2 of 6
[2023-02-10 13:02:48,835] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:02:48,847] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-09 00:00:00+00:00
[2023-02-10 13:02:48,855] {standard_task_runner.py:52} INFO - Started process 326 to run task
[2023-02-10 13:02:48,859] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'scheduled__2023-02-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpl98w7vb8', '--error-file', '/tmp/tmpk635hjem']
[2023-02-10 13:02:48,868] {standard_task_runner.py:80} INFO - Job 4: Subtask get_token
[2023-02-10 13:02:49,020] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token scheduled__2023-02-09T00:00:00+00:00 [running]> on host a299c389a304
[2023-02-10 13:02:49,276] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:00:00+00:00
[2023-02-10 13:02:49,287] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 13:02:49,295] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /app && ./script.sh ']
[2023-02-10 13:02:49,357] {subprocess.py:85} INFO - Output:
[2023-02-10 13:02:49,426] {subprocess.py:92} INFO - bash: line 1: ./script.sh: No such file or directory
[2023-02-10 13:02:49,432] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-10 13:02:49,465] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10 13:02:49,473] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230209T000000, start_date=20230210T130248, end_date=20230210T130249
[2023-02-10 13:02:49,489] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task get_token (Bash command failed. The command returned a non-zero exit code 127.; 326)
[2023-02-10 13:02:49,545] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 13:02:49,608] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
