[2023-03-25 13:52:21,859] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [queued]>
[2023-03-25 13:52:21,905] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [queued]>
[2023-03-25 13:52:21,907] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:52:21,910] {taskinstance.py:1357} INFO - Starting attempt 2 of 6
[2023-03-25 13:52:21,913] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:52:21,945] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): schedule_job_task> on 2023-03-25 13:50:12.939562+00:00
[2023-03-25 13:52:21,977] {standard_task_runner.py:52} INFO - Started process 1639 to run task
[2023-03-25 13:52:21,984] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'schedule_job_task', 'manual__2023-03-25T13:50:12.939562+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpx6mjxqc9', '--error-file', '/tmp/tmpcx1zkp6s']
[2023-03-25 13:52:21,994] {standard_task_runner.py:80} INFO - Job 95: Subtask schedule_job_task
[2023-03-25 13:52:22,109] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [running]> on host 6614738016e4
[2023-03-25 13:52:22,219] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=schedule_job_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:50:12.939562+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T13:50:12.939562+00:00
[2023-03-25 13:52:22,398] {logging_mixin.py:115} INFO - This is the response: {'node_name': 'fac540815f2e', 'status': 'ok', 'jobid': '443f1a20cb1411ed8fcb0242ac180002'}
[2023-03-25 13:52:22,400] {logging_mixin.py:115} INFO - Job scheduled successfully
[2023-03-25 13:52:22,402] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rightmove_extraction_dag.py", line 27, in schedule_job
    result = {'jobid': response_json['job_id']}
KeyError: 'job_id'
[2023-03-25 13:52:22,426] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=schedule_job_task, execution_date=20230325T135012, start_date=20230325T135221, end_date=20230325T135222
[2023-03-25 13:52:22,437] {standard_task_runner.py:92} ERROR - Failed to execute job 95 for task schedule_job_task ('job_id'; 1639)
[2023-03-25 13:52:22,503] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-25 13:52:22,533] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
