[2023-03-25 13:56:27,949] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [queued]>
[2023-03-25 13:56:27,965] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [queued]>
[2023-03-25 13:56:27,967] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:56:27,968] {taskinstance.py:1357} INFO - Starting attempt 3 of 6
[2023-03-25 13:56:27,969] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:56:27,979] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): schedule_job_task> on 2023-03-25 13:50:12.939562+00:00
[2023-03-25 13:56:27,986] {standard_task_runner.py:52} INFO - Started process 1653 to run task
[2023-03-25 13:56:27,990] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'schedule_job_task', 'manual__2023-03-25T13:50:12.939562+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpr06jvg0s', '--error-file', '/tmp/tmp1pol62ha']
[2023-03-25 13:56:27,994] {standard_task_runner.py:80} INFO - Job 96: Subtask schedule_job_task
[2023-03-25 13:56:28,092] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [running]> on host 6614738016e4
[2023-03-25 13:56:28,189] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=schedule_job_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:50:12.939562+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T13:50:12.939562+00:00
[2023-03-25 13:56:28,285] {logging_mixin.py:115} INFO - This is the response: {'node_name': 'fac540815f2e', 'status': 'ok', 'jobid': 'd6d161c2cb1411ed8fcb0242ac180002'}
[2023-03-25 13:56:28,287] {logging_mixin.py:115} INFO - Job scheduled successfully
[2023-03-25 13:56:28,289] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rightmove_extraction_dag.py", line 27, in schedule_job
    result = {'jobid': response_json['job_id']}
KeyError: 'job_id'
[2023-03-25 13:56:28,311] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=schedule_job_task, execution_date=20230325T135012, start_date=20230325T135627, end_date=20230325T135628
[2023-03-25 13:56:28,322] {standard_task_runner.py:92} ERROR - Failed to execute job 96 for task schedule_job_task ('job_id'; 1653)
[2023-03-25 13:56:28,366] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-25 13:56:28,413] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
