[2023-03-25 13:50:18,045] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [queued]>
[2023-03-25 13:50:18,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [queued]>
[2023-03-25 13:50:18,057] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:50:18,058] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-03-25 13:50:18,059] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:50:18,067] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): schedule_job_task> on 2023-03-25 13:50:12.939562+00:00
[2023-03-25 13:50:18,077] {standard_task_runner.py:52} INFO - Started process 1600 to run task
[2023-03-25 13:50:18,080] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'schedule_job_task', 'manual__2023-03-25T13:50:12.939562+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpi7hhbxvm', '--error-file', '/tmp/tmp4o0p3tme']
[2023-03-25 13:50:18,086] {standard_task_runner.py:80} INFO - Job 94: Subtask schedule_job_task
[2023-03-25 13:50:18,160] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.schedule_job_task manual__2023-03-25T13:50:12.939562+00:00 [running]> on host 6614738016e4
[2023-03-25 13:50:18,246] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=schedule_job_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:50:12.939562+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T13:50:12.939562+00:00
[2023-03-25 13:50:18,503] {logging_mixin.py:115} INFO - This is the response: <Response [200]>
[2023-03-25 13:50:18,504] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rightmove_extraction_dag.py", line 23, in schedule_job
    if response['status'] == 'ok':
TypeError: 'Response' object is not subscriptable
[2023-03-25 13:50:18,523] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=schedule_job_task, execution_date=20230325T135012, start_date=20230325T135018, end_date=20230325T135018
[2023-03-25 13:50:18,536] {standard_task_runner.py:92} ERROR - Failed to execute job 94 for task schedule_job_task ('Response' object is not subscriptable; 1600)
[2023-03-25 13:50:18,558] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-25 13:50:18,595] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
