[2023-03-27 13:43:47,036] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2023-03-27 13:43:47,044] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.schedule_job_task scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2023-03-27 13:43:47,047] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-27 13:43:47,048] {taskinstance.py:1357} INFO - Starting attempt 5 of 6
[2023-03-27 13:43:47,049] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-27 13:43:47,059] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): schedule_job_task> on 2023-03-26 00:00:00+00:00
[2023-03-27 13:43:47,067] {standard_task_runner.py:52} INFO - Started process 259 to run task
[2023-03-27 13:43:47,071] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'schedule_job_task', 'scheduled__2023-03-26T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmp23bgdlsi', '--error-file', '/tmp/tmp8ttn_qqc']
[2023-03-27 13:43:47,076] {standard_task_runner.py:80} INFO - Job 116: Subtask schedule_job_task
[2023-03-27 13:43:47,133] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.schedule_job_task scheduled__2023-03-26T00:00:00+00:00 [running]> on host 6614738016e4
[2023-03-27 13:43:47,184] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=schedule_job_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-26T00:00:00+00:00
[2023-03-27 13:43:47,221] {logging_mixin.py:115} INFO - This is the response: {'node_name': '889628ec664c', 'status': 'ok', 'jobid': '6609a17ecca511eda6b40242ac180002'}
[2023-03-27 13:43:47,222] {logging_mixin.py:115} INFO - Job scheduled successfully
[2023-03-27 13:43:47,223] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rightmove_extraction_dag.py", line 30, in schedule_job
    result = {'jobid': response_json['job_id']}
KeyError: 'job_id'
[2023-03-27 13:43:47,235] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=schedule_job_task, execution_date=20230326T000000, start_date=20230327T134347, end_date=20230327T134347
[2023-03-27 13:43:47,243] {standard_task_runner.py:92} ERROR - Failed to execute job 116 for task schedule_job_task ('job_id'; 259)
[2023-03-27 13:43:47,289] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-27 13:43:47,313] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
