[2023-02-10 12:26:03,032] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T12:17:48.218108+00:00 [queued]>
[2023-02-10 12:26:03,042] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T12:17:48.218108+00:00 [queued]>
[2023-02-10 12:26:03,044] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 12:26:03,045] {taskinstance.py:1357} INFO - Starting attempt 5 of 6
[2023-02-10 12:26:03,047] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 12:26:03,060] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-10 12:17:48.218108+00:00
[2023-02-10 12:26:03,086] {standard_task_runner.py:52} INFO - Started process 361 to run task
[2023-02-10 12:26:03,095] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'manual__2023-02-10T12:17:48.218108+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpjohr7u_d', '--error-file', '/tmp/tmp0nqrp045']
[2023-02-10 12:26:03,100] {standard_task_runner.py:80} INFO - Job 10: Subtask get_token
[2023-02-10 12:26:03,203] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T12:17:48.218108+00:00 [running]> on host 132093137b1e
[2023-02-10 12:26:03,317] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T12:17:48.218108+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T12:17:48.218108+00:00
[2023-02-10 12:26:03,322] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 12:26:03,328] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /app && ./script.sh ']
[2023-02-10 12:26:03,358] {subprocess.py:85} INFO - Output:
[2023-02-10 12:26:03,406] {subprocess.py:92} INFO - ./script.sh: line 5: gcloud: command not found
[2023-02-10 12:26:03,408] {subprocess.py:92} INFO - ./script.sh: line 9: gcloud: command not found
[2023-02-10 12:26:03,421] {subprocess.py:92} INFO - ./script.sh: line 13: gcloud: command not found
[2023-02-10 12:26:03,423] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-10 12:26:03,450] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10 12:26:03,462] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230210T121748, start_date=20230210T122603, end_date=20230210T122603
[2023-02-10 12:26:03,482] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task get_token (Bash command failed. The command returned a non-zero exit code 127.; 361)
[2023-02-10 12:26:03,524] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 12:26:03,630] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
