[2023-02-10 13:10:56,720] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T13:00:44.959479+00:00 [queued]>
[2023-02-10 13:10:56,747] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T13:00:44.959479+00:00 [queued]>
[2023-02-10 13:10:56,750] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:10:56,752] {taskinstance.py:1357} INFO - Starting attempt 6 of 6
[2023-02-10 13:10:56,753] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:10:56,769] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-10 13:00:44.959479+00:00
[2023-02-10 13:10:56,779] {standard_task_runner.py:52} INFO - Started process 431 to run task
[2023-02-10 13:10:56,784] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'manual__2023-02-10T13:00:44.959479+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpbwiw9uw8', '--error-file', '/tmp/tmpyqyq95my']
[2023-02-10 13:10:56,788] {standard_task_runner.py:80} INFO - Job 13: Subtask get_token
[2023-02-10 13:10:56,906] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T13:00:44.959479+00:00 [running]> on host a299c389a304
[2023-02-10 13:10:57,008] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T13:00:44.959479+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T13:00:44.959479+00:00
[2023-02-10 13:10:57,011] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 13:10:57,015] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /app && ./script.sh ']
[2023-02-10 13:10:57,035] {subprocess.py:85} INFO - Output:
[2023-02-10 13:10:57,128] {subprocess.py:92} INFO - bash: line 1: ./script.sh: No such file or directory
[2023-02-10 13:10:57,135] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-10 13:10:57,165] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10 13:10:57,174] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230210T130044, start_date=20230210T131056, end_date=20230210T131057
[2023-02-10 13:10:57,187] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task get_token (Bash command failed. The command returned a non-zero exit code 127.; 431)
[2023-02-10 13:10:57,205] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 13:10:57,268] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
