[2023-02-10 13:00:50,064] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T13:00:44.959479+00:00 [queued]>
[2023-02-10 13:00:50,072] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T13:00:44.959479+00:00 [queued]>
[2023-02-10 13:00:50,073] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:00:50,074] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-02-10 13:00:50,076] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 13:00:50,087] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_token> on 2023-02-10 13:00:44.959479+00:00
[2023-02-10 13:00:50,102] {standard_task_runner.py:52} INFO - Started process 300 to run task
[2023-02-10 13:00:50,110] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'get_token', 'manual__2023-02-10T13:00:44.959479+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpi52xhtw8', '--error-file', '/tmp/tmpczpnbvuu']
[2023-02-10 13:00:50,115] {standard_task_runner.py:80} INFO - Job 3: Subtask get_token
[2023-02-10 13:00:50,206] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.get_token manual__2023-02-10T13:00:44.959479+00:00 [running]> on host a299c389a304
[2023-02-10 13:00:50,284] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=get_token
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T13:00:44.959479+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T13:00:44.959479+00:00
[2023-02-10 13:00:50,287] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-02-10 13:00:50,292] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /app && ./script.sh ']
[2023-02-10 13:00:50,309] {subprocess.py:85} INFO - Output:
[2023-02-10 13:00:50,325] {subprocess.py:92} INFO - ./script.sh: line 5: gcloud: command not found
[2023-02-10 13:00:50,329] {subprocess.py:92} INFO - ./script.sh: line 9: gcloud: command not found
[2023-02-10 13:00:50,340] {subprocess.py:92} INFO - ./script.sh: line 13: gcloud: command not found
[2023-02-10 13:00:50,343] {subprocess.py:96} INFO - Command exited with return code 127
[2023-02-10 13:00:50,368] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10 13:00:50,377] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=rightmove_extraction_dag, task_id=get_token, execution_date=20230210T130044, start_date=20230210T130050, end_date=20230210T130050
[2023-02-10 13:00:50,392] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_token (Bash command failed. The command returned a non-zero exit code 127.; 300)
[2023-02-10 13:00:50,454] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 13:00:50,503] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
